### ISSUE TITLE
[BUG]: DatePicker error on Edit page

### ISSUE THREAD

**Issue by sean-nkf** [pankod/refine#1813]
Hi, I love your project very much and I'm still new to the project. I having problem when I putting in the DatePicker component into the edit form, it gave me the error message below.

**Describe the bug**
dayjs.js:212 Uncaught TypeError: date.locale is not a function
    at Object.format (dayjs.js:212:1)
    at formatValue (dateUtil.js:126:1)
    at useValueTexts.js:19:1
    at useMemo (useMemo.js:6:1)
    at useValueTexts (useValueTexts.js:8:1)
    at InnerPicker (Picker.js:142:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at mountIndeterminateComponent (react-dom.development.js:20913:1)
    at beginWork (react-dom.development.js:22416:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1)

The above error occurred in the <InnerPicker> component:

    at InnerPicker (http://localhost:3000/static/js/bundle.js:164074:32)
    at Picker (http://localhost:3000/static/js/bundle.js:164489:90)
    at LocaleReceiver (http://localhost:3000/static/js/bundle.js:107517:37)
    at Picker (http://localhost:3000/static/js/bundle.js:106484:41)
    at http://localhost:3000/static/js/bundle.js:106601:38
    at http://localhost:3000/static/js/bundle.js:83698:23
    at div
    at div
    at div
    at http://localhost:3000/static/js/bundle.js:84777:62
    at FormItemInput (http://localhost:3000/static/js/bundle.js:84048:25)
    at div
    at http://localhost:3000/static/js/bundle.js:84980:34
    at Field (http://localhost:3000/static/js/bundle.js:151017:90)
    at WrapperField (http://localhost:3000/static/js/bundle.js:151593:20)
    at FormItem (http://localhost:3000/static/js/bundle.js:83730:20)
    at form
    at Form (http://localhost:3000/static/js/bundle.js:151715:19)
    at SizeContextProvider (http://localhost:3000/static/js/bundle.js:81483:23)
    at InternalForm (http://localhost:3000/static/js/bundle.js:83508:56)
    at div
    at div
    at http://localhost:3000/static/js/bundle.js:80299:62
    at div
    at div
    at Spin (http://localhost:3000/static/js/bundle.js:94322:90)
    at SpinFC (http://localhost:3000/static/js/bundle.js:94450:34)
    at div
    at div
    at DomWrapper (http://localhost:3000/static/js/bundle.js:171277:90)
    at SingleObserver (http://localhost:3000/static/js/bundle.js:171323:24)
    at ResizeObserver (http://localhost:3000/static/js/bundle.js:171445:24)
    at PageHeader (http://localhost:3000/static/js/bundle.js:90419:88)
    at hs (http://localhost:3000/static/js/bundle.js:70291:12)
    at PostEdit (http://localhost:3000/main.60a7d0823b5bf966f488.hot-update.js:33:67)
    at Us (http://localhost:3000/static/js/bundle.js:74259:15)
    at b (http://localhost:3000/static/js/bundle.js:74338:12)
    at Outlet (http://localhost:3000/static/js/bundle.js:234711:26)
    at div
    at main
    at http://localhost:3000/static/js/bundle.js:86902:25
    at http://localhost:3000/static/js/bundle.js:86885:66
    at section
    at http://localhost:3000/static/js/bundle.js:86918:63
    at http://localhost:3000/static/js/bundle.js:86885:66
    at section
    at http://localhost:3000/static/js/bundle.js:86918:63
    at http://localhost:3000/static/js/bundle.js:86885:66
    at zo (http://localhost:3000/static/js/bundle.js:69700:15)
    at bs (http://localhost:3000/static/js/bundle.js:74157:15)
    at Routes (http://localhost:3000/static/js/bundle.js:234803:5)
    at E (http://localhost:3000/static/js/bundle.js:74448:71)
    at Router (http://localhost:3000/static/js/bundle.js:234736:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:233545:5)
    at N (http://localhost:3000/static/js/bundle.js:74544:15)
    at rr (http://localhost:3000/static/js/bundle.js:72968:15)
    at _t (http://localhost:3000/static/js/bundle.js:72664:19)
    at st (http://localhost:3000/static/js/bundle.js:71646:15)
    at cr (http://localhost:3000/static/js/bundle.js:73617:10)
    at er (http://localhost:3000/static/js/bundle.js:72911:15)
    at Zt (http://localhost:3000/static/js/bundle.js:72785:16)
    at ir (http://localhost:3000/static/js/bundle.js:73566:15)
    at Gt (http://localhost:3000/static/js/bundle.js:72629:19)
    at Ft (http://localhost:3000/static/js/bundle.js:72598:15)
    at St (http://localhost:3000/static/js/bundle.js:71096:12)
    at jt (http://localhost:3000/static/js/bundle.js:72864:11)
    at QueryClientProvider (http://localhost:3000/static/js/bundle.js:232032:21)
    at hs (http://localhost:3000/static/js/bundle.js:74017:19)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

**To Reproduce**
Create a new project according to the walkthrough steps provided tutorial (https://refine.dev/docs/ui-frameworks/antd/tutorial/)
1. Create an EditPost page
2. Adding Form.Item for the "publishedAt"
3. Go back to Posts list page and edit any error
4. See error mentioned above

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Chrome
 - Version: 101.0.4951.64 (Official Build) (x86_64)
 - Used dataProvider refine-simple-rest (https://api.fake-rest.refine.dev)

I'm using javascript and this is how I put the date picker in my EditPost page:
       <Form.Item label="Published At" name="publishedAt">
          <DatePicker />
        </Form.Item>

Appreciated. Thanks

**Comment by sean-nkf** [comment]
Hi Sorry, just realised that this issue was reported before. Thanks.

**Comment by omeraplak** [comment]
Hey @sean-nkf ,
Thank you! We are so glad you like Refine! 🎉 

For those looking for a solution to this bug in the future, here is our DatePicker example: https://refine.dev/docs/examples/inputs/datePicker/

```tsx
<Form.Item
    label="Published At"
    name="publishedAt"
    getValueProps={(value) => ({
        value: value ? dayjs(value) : "",
    })}
>
    <DatePicker />
</Form.Item>
```
